// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSSystem.Data;

#nullable disable

namespace POSSystem.Migrations
{
    [DbContext(typeof(POSDbContext))]
    partial class POSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("POSSystem.Models.CartItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactionId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("POSSystem.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("General");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresAgeVerification")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "cdba805f-9dbf-4956-81ee-5d6a740c2905",
                            Barcode = "",
                            Category = "Food",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 649, DateTimeKind.Local).AddTicks(7601),
                            Name = "Sandwich",
                            Price = 5.99m,
                            RequiresAgeVerification = false,
                            Stock = 20
                        },
                        new
                        {
                            Id = "5b9ff24d-82b9-48a9-acbf-0ebebd8547e5",
                            Barcode = "",
                            Category = "Food",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3425),
                            Name = "Hot Dog",
                            Price = 3.49m,
                            RequiresAgeVerification = false,
                            Stock = 25
                        },
                        new
                        {
                            Id = "990ecef6-dfc6-48bb-8886-38df2eaac35c",
                            Barcode = "",
                            Category = "Food",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3475),
                            Name = "Pizza Slice",
                            Price = 4.99m,
                            RequiresAgeVerification = false,
                            Stock = 15
                        },
                        new
                        {
                            Id = "3671e535-ce24-44e5-ad3f-e7bdd5ebc2fd",
                            Barcode = "",
                            Category = "Beverages",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3481),
                            Name = "Coke",
                            Price = 1.99m,
                            RequiresAgeVerification = false,
                            Stock = 50
                        },
                        new
                        {
                            Id = "f37c66b2-3b5c-46f2-9fda-a1ef9e597115",
                            Barcode = "",
                            Category = "Beverages",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3485),
                            Name = "Pepsi",
                            Price = 1.99m,
                            RequiresAgeVerification = false,
                            Stock = 50
                        },
                        new
                        {
                            Id = "92a791fd-90e6-414f-95bf-4faebfa26c64",
                            Barcode = "",
                            Category = "Beverages",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3493),
                            Name = "Water",
                            Price = 1.49m,
                            RequiresAgeVerification = false,
                            Stock = 100
                        },
                        new
                        {
                            Id = "9bc69bcb-8c19-44a2-a7da-633cb747554a",
                            Barcode = "",
                            Category = "Beverages",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3504),
                            Name = "Energy Drink",
                            Price = 3.99m,
                            RequiresAgeVerification = false,
                            Stock = 30
                        },
                        new
                        {
                            Id = "cfc49cb7-3bc2-4e67-ac7a-4c64f3a1b529",
                            Barcode = "",
                            Category = "Snacks",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3508),
                            Name = "Chips",
                            Price = 2.49m,
                            RequiresAgeVerification = false,
                            Stock = 40
                        },
                        new
                        {
                            Id = "52790d49-f6cb-484d-b36d-24455de084b2",
                            Barcode = "",
                            Category = "Snacks",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3511),
                            Name = "Chocolate",
                            Price = 1.99m,
                            RequiresAgeVerification = false,
                            Stock = 60
                        },
                        new
                        {
                            Id = "f6d729da-62c1-4efd-be96-751cd47abfd3",
                            Barcode = "",
                            Category = "Snacks",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3516),
                            Name = "Candy Bar",
                            Price = 1.49m,
                            RequiresAgeVerification = false,
                            Stock = 75
                        },
                        new
                        {
                            Id = "98129e0b-27d7-41e5-9d6c-1cb22abf40df",
                            Barcode = "",
                            Category = "Snacks",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3519),
                            Name = "Gum",
                            Price = 1.99m,
                            RequiresAgeVerification = false,
                            Stock = 50
                        },
                        new
                        {
                            Id = "b28ff8b5-4f9e-4a14-a454-e860d1b67ed8",
                            Barcode = "123456789",
                            Category = "18+",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3522),
                            Name = "Cigarettes",
                            Price = 15.99m,
                            RequiresAgeVerification = true,
                            Stock = 20
                        },
                        new
                        {
                            Id = "375b9ada-3514-4c44-afe9-32f2bc474dd7",
                            Barcode = "987654321",
                            Category = "18+",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3526),
                            Name = "Tobacco",
                            Price = 12.99m,
                            RequiresAgeVerification = true,
                            Stock = 15
                        },
                        new
                        {
                            Id = "fd5d4414-8ecf-4860-81ca-670d6c8642cb",
                            Barcode = "",
                            Category = "Misc",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3529),
                            Name = "Magazine",
                            Price = 4.99m,
                            RequiresAgeVerification = false,
                            Stock = 30
                        },
                        new
                        {
                            Id = "b3600389-3d89-4276-9c80-14640078d9ee",
                            Barcode = "",
                            Category = "Misc",
                            CreatedDate = new DateTime(2026, 4, 16, 1, 20, 23, 652, DateTimeKind.Local).AddTicks(3535),
                            Name = "Batteries",
                            Price = 6.99m,
                            RequiresAgeVerification = false,
                            Stock = 25
                        });
                });

            modelBuilder.Entity("POSSystem.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AgeVerified")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Change")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("POSSystem.Models.CartItem", b =>
                {
                    b.HasOne("POSSystem.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("POSSystem.Models.Transaction", null)
                        .WithMany("Cart")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("POSSystem.Models.Transaction", b =>
                {
                    b.Navigation("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}
